INSERT INTO `question` (`id`, `question`) VALUES
(1, 'Que signifie le sigle IST ?'),
(2, 'Par quels types de rapports une IST peut-elle se transmettre ?'),
(3, 'Une personne peut-elle avoir une IST sans symptôme ?'),
(4, 'Quel est l''intérêt du dépistage des IST ?'),
(5, 'Quel moyen réduit fortement le risque de nombreuses IST lorsqu''il est bien utilisé ?'),
(6, 'Quel énoncé sur la PrEP VIH est correct ?'),
(7, 'Après une exposition récente au VIH, que faut-il faire pour envisager un TPE ?'),
(8, 'Contre quelles IST existe-t-il des vaccins utilisés en prévention ?'),
(9, 'Quel énoncé sur le VIH est vrai ?'),
(10, 'Que signifie l''idée ''indétectable = intransmissible'' pour le VIH ?'),
(11, 'Quel comportement est recommandé avant d''arrêter le préservatif avec un nouveau partenaire stable ?'),
(12, 'Pourquoi le préservatif ne supprime-t-il pas 100 % du risque pour toutes les IST ?'),
(13, 'Quel lubrifiant est compatible avec un préservatif en latex ?'),
(14, 'Pourquoi faut-il éviter les corps gras avec un préservatif en latex ?'),
(15, 'Quelle bonne pratique concerne l''utilisation du préservatif ?'),
(16, 'Que faut-il vérifier avant d''utiliser un préservatif ?'),
(17, 'Quel énoncé est correct à propos des contraceptifs hormonaux comme la pilule ?'),
(18, 'La contraception d''urgence protège-t-elle des IST après un rapport à risque ?'),
(19, 'Quel est l''intérêt d''une digue dentaire ?'),
(20, 'Les objets sexuels partagés peuvent-ils participer à la transmission d''IST ?'),
(21, 'Que faire pour réduire le risque avec un sextoy partagé ?'),
(22, 'Quelle affirmation sur la chlamydia est juste ?'),
(23, 'Pourquoi traiter une infection à chlamydia est important ?'),
(24, 'Quel énoncé sur la gonorrhée est correct ?'),
(25, 'Pourquoi ne faut-il pas traiter une gonorrhée avec des antibiotiques restants ?'),
(26, 'Quel signe peut évoquer une syphilis au début ?'),
(27, 'La syphilis peut-elle avoir des complications graves si elle n''est pas traitée ?'),
(28, 'Quel énoncé sur l''herpès génital est exact ?'),
(29, 'L''herpès peut-il se transmettre en dehors d''une poussée visible ?'),
(30, 'Quelle infection peut être prévenue par un vaccin et se transmettre sexuellement ou par le sang ?'),
(31, 'Quel organe peut être gravement atteint par l''hépatite B chronique ?'),
(32, 'Quel énoncé sur l''hépatite C est le plus juste ?'),
(33, 'Pourquoi le dépistage après un rapport à risque doit parfois être répété ?'),
(34, 'Pour un test VIH de laboratoire de type ELISA, à quel délai un résultat est généralement considéré fiable après une exposition ?'),
(35, 'Pour un autotest ou un TROD VIH, quel délai est généralement nécessaire après une exposition pour un résultat fiable ?'),
(36, 'En France, que permet le dispositif Mon test IST en laboratoire ?'),
(37, 'Quel lieu peut proposer information, dépistage et diagnostic gratuits des IST en France ?'),
(38, 'Pourquoi prévenir ses partenaires après un diagnostic d''IST est utile ?'),
(39, 'Pourquoi les partenaires doivent-ils parfois être traités en même temps ?'),
(40, 'Pendant le traitement d''une IST, quelle attitude est généralement prudente ?'),
(41, 'Quel type d''IST est traité par antibiotiques lorsqu''un médecin le prescrit ?'),
(42, 'Pourquoi faut-il terminer un traitement antibiotique prescrit contre une IST ?'),
(43, 'Quel énoncé sur le HPV est exact ?'),
(44, 'La vaccination HPV a surtout quel objectif ?'),
(45, 'Quel dépistage reste important pour les personnes concernées même vaccinées contre le HPV ?'),
(46, 'Quel énoncé sur les symptômes d''IST est correct ?'),
(47, 'Une IST de la gorge ou du rectum peut-elle être asymptomatique ?'),
(48, 'Quel rapport peut transmettre certaines IST même sans pénétration vaginale ou anale ?'),
(49, 'Quelle affirmation sur le baiser est la plus prudente ?'),
(50, 'Le VIH se transmet-il par les moustiques ?'),
(51, 'Le VIH se transmet-il par une poignée de main ou une accolade ?'),
(52, 'Quels liquides peuvent transmettre le VIH dans des conditions de risque ?'),
(53, 'Quel geste réduit le risque de VIH, hépatite B et hépatite C chez les personnes qui s''injectent des produits ?'),
(54, 'Pourquoi le nombre de partenaires peut-il influencer le risque d''IST ?'),
(55, 'Quel énoncé est juste sur une relation exclusive ?'),
(56, 'Pourquoi parler de dépistage avec un partenaire est utile ?'),
(57, 'Quel effet l''alcool ou certaines drogues peuvent-ils avoir sur le risque d''IST ?'),
(58, 'Quelle attitude est correcte en cas de rapport non consenti ou de doute après une exposition ?'),
(59, 'Quel énoncé sur les morpions ou la gale est vrai ?'),
(60, 'La trichomonase est causée par quel type d''agent ?'),
(61, 'Quel énoncé sur la grossesse et les IST est correct ?'),
(62, 'Quel symptôme urinaire doit faire penser à consulter après un rapport à risque ?'),
(63, 'Les pertes vaginales inhabituelles après un rapport à risque doivent-elles être prises au sérieux ?'),
(64, 'Quel énoncé sur l''automédication est correct ?'),
(65, 'Pourquoi une consultation est importante en cas de plaie génitale ?'),
(66, 'Quel énoncé sur les tests de dépistage est juste ?'),
(67, 'Pourquoi faut-il parfois faire un prélèvement de gorge ou rectal ?'),
(68, 'Quel message est correct sur les IST et l''apparence d''une personne ?'),
(69, 'Quel est le rôle du préservatif interne ?'),
(70, 'Pourquoi ne faut-il pas mettre un préservatif externe et un préservatif interne en même temps ?'),
(71, 'Quand faut-il mettre un préservatif externe pour qu''il protège correctement ?'),
(72, 'Que faire si un préservatif craque pendant un rapport à risque ?'),
(73, 'Quel énoncé sur le dépistage régulier est pertinent ?'),
(74, 'Quelle affirmation sur la PrEP est correcte ?'),
(75, 'Quel énoncé sur le TPE est correct ?'),
(76, 'Quel est un avantage de combiner plusieurs moyens de prévention ?'),
(77, 'Quel énoncé sur le traitement d''une personne vivant avec le VIH est correct ?'),
(78, 'Quel message est exact sur les IST virales comme HPV, herpès ou VIH ?'),
(79, 'Quel énoncé sur les IST bactériennes est correct ?'),
(80, 'Quel est un bon réflexe après un résultat positif à une IST ?'),
(81, 'Quel énoncé est correct sur les tests en vente ou autotests VIH ?'),
(82, 'Pourquoi le dépistage du VIH peut-il être proposé avec celui d''autres IST ?'),
(83, 'Quelle phrase décrit correctement le risque lors du sexe anal non protégé ?'),
(84, 'Pourquoi utiliser assez de lubrifiant lors d''une pénétration anale peut aider à la prévention ?'),
(85, 'Quel énoncé sur les infections à HPV est prudent ?'),
(86, 'Quel énoncé sur les verrues génitales est exact ?'),
(87, 'Que signifie un dépistage négatif trop tôt après une prise de risque ?'),
(88, 'Quel énoncé sur le consentement est lié à la prévention ?'),
(89, 'Quelle est une limite de l''auto-évaluation des symptômes ?'),
(90, 'Quel énoncé sur les douches vaginales ou intimes après un rapport est correct ?'),
(91, 'Quel comportement protège contre la réinfection après une IST traitée ?'),
(92, 'Quel énoncé sur les rapports oraux est exact ?'),
(93, 'Quel moyen barrière peut être utilisé pour une fellation afin de réduire le risque d''IST ?'),
(94, 'Quel moyen barrière peut être utilisé pour un cunnilingus ou anulingus afin de réduire le risque ?'),
(95, 'Que faire si l''on apprend qu''un partenaire a une IST ?'),
(96, 'Quel énoncé sur la confidentialité du dépistage en France est correct ?'),
(97, 'Quel est un message exact sur les IST et l''hygiène ?'),
(98, 'Pourquoi les informations médicales personnalisées doivent-elles venir d''un professionnel de santé ?'),
(99, 'Quelle combinaison décrit bien une prévention sexuelle complète ?'),
(100, 'Quel objectif principal vise l''éducation sur les IST ?');
