# Configuration Accès JPA
spring.datasource.url = jdbc:mysql://localhost:3306/istedex?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password = root

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

# Cle secrete JWT fournie par variable d'environnement
# TODO: Récuperer la clé JWT depuis une variable d'envirronement - jwt.key = ${JWT_KEY}
jwt.key = K0kRSomEw3pXsI1Euim9Zh5LzZxQ1H19LTwuizBv/FY=


