# Configuration Accès JPA
spring.datasource.url = jdbc:mysql://localhost:3306/istedex?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password = root

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

# Changer le port utilisé par le Tomcat embarqué
# server.port = 8081

# Ajouter un chemin à la racine du projet : http://localhost:8080/leprojet/blabla
# server.servlet.context-path = /leprojet/
